"""empty message

Revision ID: 7a57a86d8603
Revises: ca2e990e6a53
Create Date: 2025-09-03 15:14:27.038151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a57a86d8603'
down_revision = 'ca2e990e6a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_school_map',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=64), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admin_id', 'school_id', name='uq_admin_school')
    )
    with op.batch_alter_table('admin_school_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_school_map_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_school_map_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_school_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_school_map_school_id'))
        batch_op.drop_index(batch_op.f('ix_admin_school_map_admin_id'))

    op.drop_table('admin_school_map')
    # ### end Alembic commands ###
